### ISSUE TITLE
suggest correct tags 

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/CakeContrib.Guidelines#100]
Which will lead to NuGet showing the correct installation instructions.

So: Suggest using `cake-addin` or, (when #91 is done) `cake-module`.

Probably suggest this, only if a nupkg is generated from the project.

**Comment by gep13** [comment]
Is there some additional work needed in the Cake Addin Discover to ignore the new tags that are going to be suggested here? /cc @Jericho

**Comment by Jericho** [comment]
Only need to add the tags to the exclusion list

**Comment by nils-a** [comment]
I have created https://github.com/cake-contrib/Cake.AddinDiscoverer/issues/182 to track that.

**Comment by nils-a** [comment]
Are there more tags we should suggest? Most packages seem to be tagged using `cake`, `script`, `build`

**Comment by augustoproiete** [comment]
The other tags are only to help with discovery on NuGet.org, isn't it?

`cake`, `addin`, `cake-build`, `script`, `build` ?

**Comment by nils-a** [comment]
When #112  is done, we should also suggest `cake-recipe` as a tag for recipe projects.
