### ISSUE TITLE
CakeContrib.Guidelines should be marked developmentDependency

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/CakeContrib.Guidelines#18]
Since CakeContrib.Guidelines is a *utility* to help/guide with development it is only needed during build-time of the project it is included in.

Therefore the nuspec should contain `<developmentDependency>true</developmentDependency>` to  prevent the package from being included as a dependency in other packages.
Also, this will lead to `PrivateAssets` being set (automatically) in consuming [packages using `PackageReference`](https://github.com/NuGet/Home/wiki/DevelopmentDependency-support-for-PackageReference).

For consistency with #6 having `<PrivateAssets>all</PrivateAssets>` on a reference to CakeContrib.Guidelines should also be checked/validated.

**Comment by gep13** [comment]
@nils-a this is a great suggestion.

Can we also have the same check on `Cake.Addin.Analyzer` package, which we are also recommending that folks use?

**Comment by AdmiringWorm** [comment]
@gep13 @nils-a just FYI, the Cake.Addin.Analyzer will automatically install itself as a private asset (if installed through Visual Studio, or through the .NET Core utility).

Still a :+1: from me though, in case people add it manually.

**Comment by nils-a** [comment]
@AdmiringWorm yes, CakeContrib.Guidelines will now install that way, too :-)
