### ISSUE TITLE
Supported frameworks since Cake 3.0 are net7.0 and net6.0

### ISSUE THREAD

**Issue by devlead** [cake-contrib/CakeContrib.Guidelines#217]
Guidance needs to be updated 
https://github.com/cake-contrib/CakeContrib.Guidelines/blob/10515df04f9d3ff65dd6dcbfc042200a09ee3cba/src/Tasks/TargetFrameworkVersions.cs#L40-L42

Need to add 3.0 similar too

https://github.com/cake-contrib/CakeContrib.Guidelines/blob/10515df04f9d3ff65dd6dcbfc042200a09ee3cba/src/Tasks/TargetFrameworkVersions.cs#L89-L105

**Comment by nils-a** [comment]
Fixed in #218

**Comment by nils-a** [comment]
@all-contributors please add @devlead for bug.
