### ISSUE TITLE
Check for multi-targeting

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/CakeContrib.Guidelines#48]
https://github.com/cake-contrib/Home/blob/master/Guidelines.md suggests:

> [to] multi-target addins to netstandard2.0 and net461 to have the maximum compatibility.

This should be implemented as a check.

**Comment by Jericho** [comment]
FYI: the way this is analyzed in the AddinDiscoverer is to check if the addin targets `netstandard2.0` **at a minimum** and `net46` or `net461` **optionally**.

In fact, there is a matrix of "required" frameworks and "optional" frameworks depending on the version of Cake being targeted. This matrix will probably grow in the future when Cake targets new frameworks.

**Comment by nils-a** [comment]
@Jericho good to know. Is that "matrix" documented somewhere or only at https://github.com/cake-contrib/Cake.AddinDiscoverer/blob/develop/Source/Cake.AddinDiscoverer/Utilities/Constants.cs#L36

**Comment by Jericho** [comment]
The code you reference is indeed the matrix I’m talking about. It’s based on numerous discussion on Gitter, Slack, etc. Nothing in written form that I’m aware.
