### ISSUE TITLE
Add rule to suggest `net5.0` target for v1.0 release

### ISSUE THREAD

**Issue by augustoproiete** [cake-contrib/CakeContrib.Guidelines#76]
With Cake v1.0 release, I believe we'll be recommending addins to multi-target `net5.0`, `netstandard2.0`, and `net461` for broader reach.

It seems it would be an update to `CCG0007`.

**Comment by AdmiringWorm** [comment]
Just a note, should maybe take the cake version into account as well.

If the project references a version of cake below 1.0.0, only suggest netstandard and net461, but otherwise suggest all three (not sure if it is possible though).

**Comment by nils-a** [comment]
Yes, I planned on that.

**Comment by nils-a** [comment]
probably related to #91
