### ISSUE TITLE
Honor existing icon

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/CakeContrib.Guidelines#80]
When I added the guidelines package to my addin, it created a new icon file and directed me to change the project properties to use this new icon despite the fact that my addin already uses the cake-contrib icon but with a different name.

Is it possible to honor the existing icon?

If so, maybe check the binary content of the existing icon and compare it with the binary content of the cake-contrib icon to ensure the author is using the desired png file.

**Comment by nils-a** [comment]
@Jericho the location of the icon can be changed using
```xml
<PropertyGroup>
    <IconDestinationLocation>my-cool-logo.png</IconDestinationLocation>
</PropertyGroup>
```

However, that will override your icon with the "official" one.  If I understand you correct you'd rather have a check if the current icon is the "correct" icon and probably raise a warning rather than overriding the icon?

Additionally you probably have an include like 
```xml
<ItemGroup>
    <None Include="my-cool-icon.png">
        <Pack>True</Pack>
        <PackagePath></PackagePath>
    </None>
</ItemGroup> 
``` 
This should either be removed, or the automatic include of the icon should be omitted like so:
```xml
<PropertyGroup>
    <CakeContribGuidelinesIconOmitImport>1</CakeContribGuidelinesIconOmitImport>
</PropertyGroup>
```

**Comment by Jericho** [comment]
It's great that there is a way to manually override the name of the icon but the point I was trying to make is that it would be much more user-friendly to automatically detect if there is already an icon included in the project and honor it. In other words: why should I need to add `IconDestinationLocation` in my csproj when I already have 
```xml
<PackageIcon>my-cool-icon.png</PackageIcon>
``` 
combined with 
```xml
  <ItemGroup>
    <None Include="..\my-cool-icon.png" Pack="true" PackagePath="" />
  </ItemGroup>
```

Secondarily, I was suggesting comparing the binary content of the current icon with the binary content of the cake-contrib icon and to throw a warning and/or overwrite the icon if and only if the content does not match.
