### ISSUE TITLE
Incorrect URL for warning details

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/CakeContrib.Guidelines#81]
I get the following warning in my project:
![image](https://user-images.githubusercontent.com/112710/108096927-81f55b80-704f-11eb-8e21-381e7214ebee.png)

When I click the link to read more details, I get redirected to the following URL:
https://docs.microsoft.com/en-us/visualstudio/?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(CCG0002)%26rd%3Dtrue&view=vs-2019.

I suspect the intent is to redirect me to this URL: https://cake-contrib.github.io/CakeContrib.Guidelines/rules/ccg0002

**Comment by nils-a** [comment]
Sadly, no. 

The generation of the clickable links is VS-dependent and Visual Studio chooses to display a link to docs.microsoft.com. VS-Code or Rider for example do not render something clickable at all.
I've started to inquire about the possibilities (or rather the lack thereof) here: https://github.com/MicrosoftDocs/visualstudio-docs/issues/5894 but it seems no-one really knows what VS does under the hood.

I could investigate if, when we added our own url-links to the end of the warning, those would be clickable. (Or rather if that would still look somewhat decent...)

**Comment by augustoproiete** [comment]
@nils-a It looks like more recent versions of MSBuild introduces an overload where you can specify a [`HelpLink`](https://github.com/dotnet/msbuild/pull/5488) when logging warnings add errors, which (in theory) lets us override the default URL that uses the help keyword.

https://github.com/dotnet/msbuild/blob/master/ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs#L426

**Comment by nils-a** [comment]
@augustoproiete right, seems that PR was merged a couple of days after I made the comment in the docs issue.
So if I interpret the releases right, we could be using that when compiling is done using .NET 5 (or MSBuild 16.7)

**Comment by Jericho** [comment]
I see. It's really too bad that we can't customize the URL.

**Comment by augustoproiete** [comment]
@nils-a This project already references [Microsoft.Build.Utilities.Core v16.8.0](https://github.com/cake-contrib/CakeContrib.Guidelines/blob/02d8e180c780b9921c4b5e4129c542b5a4f0a0e8/src/Tasks/Tasks.csproj#L16) which contains the overload already, so we should be able to use it today, with or without .NET 5

![image](https://user-images.githubusercontent.com/177608/108122279-6b182e80-707a-11eb-8867-119cb88e6011.png)

**Comment by nils-a** [comment]
@all-contributors please add @Jericho for bug and ideas
