### ISSUE TITLE
documentation needs a "better" place

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/CakeContrib.Guidelines#9]
currently everything is in the README.md.

It should either be moved to gh-wiki or into gh-pages (but that requires an organization)

**Comment by gep13** [comment]
@nils-a how would you feel about moving this repo under the cake-contrib Organisation?  Obviously you would have full control over it.

@admiringworm has some pretty cool docs on the go for his analyzer:

https://wormiecorp.github.io/Cake.Addin.Analyzer/rules/

**Comment by nils-a** [comment]
@gep13 I would be happy to move it into cake-contrib.

(And yes - I saw what @AdmiringWorm did there..  👍)
